services:
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elasticsearch-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elasticsearch-network

  python-elasticsearch:
    container_name: python-elasticsearch
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    networks:
      - elasticsearch-network
    tty: true
    stdin_open: true

networks:
  elasticsearch-network:
    driver: bridge
    external: true